### ISSUE TITLE
这个项目还更新吗 我对这个感兴趣

### ISSUE THREAD

**Issue by 2439905184** [surunzi/WebVN#3]
但不知道从哪里开始看代码,也没有说明文件,写明webvn的设计思路,逻辑。
我自己也在写视觉小说框架
使用的是jquery库,css3
存储使用的是cookie,localStorage。
代码比较简单,刚开始搞。
不同的功能也是分不同的模块 js文件
使用的是工程模式,也没有使用Emascript的特性,就纯js+jquery。
这里是项目地址:https://github.com/little-game-and-simple-software/EasyAvgFrameWork

**Comment by 2439905184** [comment]
shader我也不会写,但你那个deno的效果我觉得是真的好

**Comment by surunzi** [comment]
不会更新了，工作比较忙。以后有机会可能会搞，不过搞也应该是重新开新坑。。
